### ISSUE TITLE
video.mp4 are missing in UCSD dataset

### ISSUE THREAD

**Issue by guybartal** [microsoft/MLOps_VideoAnomalyDetection#4]
video files are missing from [UCSD dataset](http://www.svcl.ucsd.edu/projects/anomaly/dataset.htm), where did you get them from?

**Comment by wmpauli** [comment]
Thank you for bringing this up. I added a small bash script in `tools` that allows you to create the videos from the individual files. Please let me know if it doesn't work. 

Alternatively, you could also just remove the first step in the aml pipelines (decode_videos).

**Comment by wmpauli** [comment]
Thank you for bringing this up. I added a small bash script in `tools` that allows you to create the videos from the individual files. Please let me know if it doesn't work. 

Alternatively, you could also just remove the first step in the aml pipelines (decode_videos).
