### ISSUE TITLE
trying to use the project

### ISSUE THREAD

**Issue by micuentadecasa** [microsoft/MLOps_VideoAnomalyDetection#7]
dear all,

I was trying your project but I have found some issues, I was following your steps and this is what I have found:
1. I downloaded the UCS dataset and executed the data_prepraration.py file (note that in your documents the name of the file is shorter. It seems to be executed ok, but the files are not in the right folder, see next section.
2 as said the documents created in the point 1 are placed in a different place (it puts it into a folder, I had to move them to the root of data folder.
in addition there is a typo in the file prednet.py, it puts .BACKEND and it should be lowercase
and at the end I got an error that I put below:

 /keras_preprocessing/image/iterator.py line 127 in _get_batches_of_transformed_samples raise NotImplementedError

keras is version 2.3.1

I hope that you can help me to fix this issue and continue with the testing.

regards.

**Comment by micuentadecasa** [comment]
I solved point 2, I looked at  MLOps_VideoAnomalyDetection/deployment/create_docker_image.py
 file and installed the right versions of the modules

cd = CondaDependencies.create(pip_packages=['keras==2.0.8', 'theano', 'tensorflow==1.8.0', 'matplotlib', 'hickle', 'pandas', 'azureml-sdk'])

I think that it is recommended to put a requirements.txt file, so people can install without these errors

**Comment by wmpauli** [comment]
Thanks for the feedback. The code has been refactored quite a bit now. I prefer to use conda environment definitions, because it allows my to also have non-pip dependencies (e.g. cudatoolkit). Hope this works now.
