### ISSUE TITLE
bug in train.py

### ISSUE THREAD

**Issue by micuentadecasa** [microsoft/MLOps_VideoAnomalyDetection#8]
dear all,

I have found a bug in the code, in train.py, in line 294, you call the function run without taking into account if the training is done in remote

```
_# after training is complete, we log the final loss on the validation set
run.log('final_val_loss', history.history['val_loss'][-1])_
```

it should be 

```
_# after training is complete, we log the final loss on the validation set
if remote_execution:
      run.log('final_val_loss', history.history['val_loss'][-1])_
```

**Comment by uname0x96** [comment]
you just need try to defind 1 custom func for write it.

**Comment by wmpauli** [comment]
Thanks. The sdk should catch that and simply print a warning that it didn't log to aml because running locally.
